# Generated by Django 5.0 on 2024-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_price_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='type',
            field=models.CharField(choices=[('demo', 'Demo'), ('full', 'Full Course')], default='full', max_length=10),
        ),
    ]
