# Generated by Django 5.0 on 2024-09-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_order_unique_together_enrollment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_posts/'),
        ),
    ]
