# Generated by Django 5.0 on 2024-09-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('demo', 'Demo'), ('full', 'Full Course')], default='unspecified', max_length=20),
        ),
    ]
