# Generated by Django 5.0 on 2024-09-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('institute', models.CharField(max_length=200, verbose_name='Institute')),
                ('employer', models.CharField(blank=True, max_length=200, verbose_name='Who do you work for?')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Designation (if agency)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('contact_type', models.CharField(choices=[('individual', 'Individual'), ('agency', 'Agency'), ('institution', 'Institution'), ('organisation', 'Organisation')], max_length=50, verbose_name='Type')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_full_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('enrollment_type', models.CharField(choices=[('demo', 'Demo'), ('full', 'Full Course')], max_length=4)),
                ('enrollment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
